// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LayersUIClient is the client API for LayersUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LayersUIClient interface {
	// ListEngineSpecs returns a list of Layers Engine(s) that can be started through the UI.
	ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (LayersUI_ListEngineSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type layersUIClient struct {
	cc grpc.ClientConnInterface
}

func NewLayersUIClient(cc grpc.ClientConnInterface) LayersUIClient {
	return &layersUIClient{cc}
}

func (c *layersUIClient) ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (LayersUI_ListEngineSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &LayersUI_ServiceDesc.Streams[0], "/v1.LayersUI/ListEngineSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &layersUIListEngineSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LayersUI_ListEngineSpecsClient interface {
	Recv() (*ListEngineSpecsResponse, error)
	grpc.ClientStream
}

type layersUIListEngineSpecsClient struct {
	grpc.ClientStream
}

func (x *layersUIListEngineSpecsClient) Recv() (*ListEngineSpecsResponse, error) {
	m := new(ListEngineSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *layersUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.LayersUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LayersUIServer is the server API for LayersUI service.
// All implementations must embed UnimplementedLayersUIServer
// for forward compatibility
type LayersUIServer interface {
	// ListEngineSpecs returns a list of Layers Engine(s) that can be started through the UI.
	ListEngineSpecs(*ListEngineSpecsRequest, LayersUI_ListEngineSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedLayersUIServer()
}

// UnimplementedLayersUIServer must be embedded to have forward compatible implementations.
type UnimplementedLayersUIServer struct {
}

func (UnimplementedLayersUIServer) ListEngineSpecs(*ListEngineSpecsRequest, LayersUI_ListEngineSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListEngineSpecs not implemented")
}
func (UnimplementedLayersUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedLayersUIServer) mustEmbedUnimplementedLayersUIServer() {}

// UnsafeLayersUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LayersUIServer will
// result in compilation errors.
type UnsafeLayersUIServer interface {
	mustEmbedUnimplementedLayersUIServer()
}

func RegisterLayersUIServer(s grpc.ServiceRegistrar, srv LayersUIServer) {
	s.RegisterService(&LayersUI_ServiceDesc, srv)
}

func _LayersUI_ListEngineSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEngineSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LayersUIServer).ListEngineSpecs(m, &layersUIListEngineSpecsServer{stream})
}

type LayersUI_ListEngineSpecsServer interface {
	Send(*ListEngineSpecsResponse) error
	grpc.ServerStream
}

type layersUIListEngineSpecsServer struct {
	grpc.ServerStream
}

func (x *layersUIListEngineSpecsServer) Send(m *ListEngineSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _LayersUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LayersUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.LayersUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LayersUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LayersUI_ServiceDesc is the grpc.ServiceDesc for LayersUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LayersUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.LayersUI",
	HandlerType: (*LayersUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _LayersUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEngineSpecs",
			Handler:       _LayersUI_ListEngineSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "layers-ui.proto",
}
